name: 🐛 Bug Report
description: "Create a bug report to help us improve ZITADEL Terrafform Provider."
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: checkboxes
  id: preflight
  attributes:
    label: Preflight Checklist
    options:
    - label:
        I could not find a solution in the documentation, the existing issues or discussions
      required: true
    - label:
        I have joined the [ZITADEL chat](https://zitadel.com/chat)
- type: input
  id: version
  attributes:
    label: Version
    required: true
    description: Which version of the Terrafor Provider are you using.
- type: input
  id: zitadelversion
  attributes:
    label: ZITADEL Version
    description: Which version of ZITADEL are you using.
- type: textarea
  id: impact
  attributes:
    label: Describe the problems caused by this bug
    description: A clear and concise description of what the problems you face and the bug you have.
  validations:
    required: true
