name: Test Provider

on: pull_request

jobs:
  test:

    runs-on: ubuntu-20.04

    permissions:
      contents: read

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Download Go Modules
      run: go mod download

    - name: Make Machinekey Directory Writable
      working-directory: acceptance
      run: "chmod -R 777 keys"

    - name: Setup ZITADEL
      working-directory: acceptance
      run: docker compose run setup

    - name: Run Acceptance Tests
      run: TF_ACC=1 go test ./...

    - name: Save Docker Compose Logs
      working-directory: acceptance
      if: always()
      run: docker compose logs > .docker-compose.log

    - name: Archive Docker Compose Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pull-request-tests
        path: |
          acceptance/.docker-compose.log
        retention-days: 30
