name: Test Provider

on: pull_request

jobs:
  test:

    runs-on: ubuntu-20.04

    permissions:
      contents: read

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up ZITADEL
      working-directory: acceptance
      run: docker compose run wait_for_zitadel

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run Acceptance Tests
      run: TF_ACC=1 TF_ACC_ZITADEL_TOKEN=$(pwd)/acceptance/machinekey/zitadel-admin-sa.json go test ./...

    - name: Save ZITADEL Logs
      if: always()
      run: docker compose logs zitadel > .zitadel.log

    - name: Archive ZITADEL Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pull-request-tests
        path: |
          .zitadel.log
        retention-days: 30
