name: Test Provider

on: pull_request

jobs:
  test:

    runs-on: ubuntu-20.04

    permissions:
      contents: read

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Make Machinekey Directory Writable
      working-directory: acceptance
      run: "chmod -R 777 keys"

    - name: Setup ZITADEL
      working-directory: acceptance
      run: docker compose run setup

    - name: Set Cache Variables
      id: go-cache-variables
      run: |
        echo "GO_CACHE_PATH=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "GO_CACHE_KEY_PREFIX=${GO_CACHE_KEY_PREFIX}" >> $GITHUB_OUTPUT
        echo "GO_CACHE_KEY=${GO_CACHE_KEY_PREFIX}${{ hashFiles( 'go.*', 'acceptance', 'zitadel/**/*.go') }}" >> $GITHUB_OUTPUT
      env:
        GO_CACHE_KEY_PREFIX: acceptance-test-

    - name: Restore Previous Results
      uses: actions/cache/restore@v3
      id: cache
      timeout-minutes: 1
      with:
        key: ${{ steps.go-cache-variables.outputs.GO_CACHE_KEY }}
        restore-keys: ${{ steps.go-cache-variables.outputs.GO_CACHE_KEY_PREFIX }}
        path: ${{ steps.go-cache-variables.outputs.GO_CACHE_PATH }}

    - name: Download Go Modules
      run: go mod download

    - name: Run Acceptance Tests
      run: TF_ACC=1 go test ./...

    - name: Cache Results
      if: always()
      uses: actions/cache/save@v3
      with:
        key: ${{ steps.go-cache-variables.outputs.GO_CACHE_KEY }}
        path: ${{ steps.go-cache-variables.outputs.GO_CACHE_PATH }}

    - name: Save Docker Compose Logs
      if: always()
      working-directory: acceptance
      run: docker compose logs > .docker-compose.log

    - name: Archive Docker Compose Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pull-request-tests
        path: |
          acceptance/.docker-compose.log
        retention-days: 30
